#!/bin/bash
path="../experiments/gauss_delay_025_blocked_2019-03-05_12-33"

if [ ! -d "$path/results" ]
then
    echo "$path/results"
    mkdir -p "$path/results"
fi

for filename in $path/*
do
  File="$filename/exp_result.txt"
  if [ -e $File ]
  then
    #-ls $filename
    Stable="0"
    bridge="1"
    dissolution="1"
    Name=$(basename $filename)

    Angle=$(echo $Name | awk -F'[_]' '{print $2}')
    echo "Angle is $Angle"
    Height="$(sed -n 's/Height: \(.*\)/\1/p' < $File)"

    delay=$(echo $Name | awk -F'[_]' '{print $6}')
    echo "Delay is $delay"

    dist="$(sed -n 's/Distance between robots: \(.*\)/\1/p' < $File)"
    dist=$(echo $dist | awk -F'[ ]' '{print $1}')

    phase="$(sed -n 's/Phase shift between robots: \(.*\)/\1/p' < $File)"
    phase=$(echo $phase | awk -F'[ ]' '{print $1}')

    form_duration="$(sed -n 's/Bridge formation step duration: \(.*\)/\1/p' < $File)"
    form_duration=$(echo $form_duration | awk -F'[ ]' '{print $1}')
#    dist="$(cut -d' ' -f1 <<<$dist)"
    if grep -q STABLE "$File";
    then
      Stable="1"
    fi
    if grep -q 'No bridge has formed' "$File"
    then
      bridge="0"
      Nb_r="0"
    else
      Nb_r="$(sed -n 's/Number of robots in the bridge: \(.*\)/\1/p' < $File)"
      Nb_r=$(echo $Nb_r| awk -F'[  ]' '{print $1}')
    fi
    if grep -q 'Bridge dissolution has not been reached' "$File"
    then
      dissolution="0"
      Nb_r_diss="$(sed -n 's/Number of robots in the bridge: \(.*\)/\1/p' < $File)"
      Nb_r_diss=$(echo $Nb_r_diss | awk -F'[  ]' '{print $2}')
    else
      Nb_r_diss="$(sed -n 's/Number of robots blocked: \(.*\)/\1/p' < $File)"
    fi

    echo "$Angle; $Height; $delay; $dist; $phase; $bridge; $form_duration; $Stable; $Nb_r; $dissolution; $Nb_r_diss"  >> $path/results/nb_robots.txt
#    echo "$Angle; $Height; $dist; $Stable; $Nb_r"  >> $path/results/nb_robots.txt
  fi
done
